config/routes.rb
Shoppe::Engine.routes.draw do
  resources :posts do
    post :search, on: :collection
    resources :addresses
  end
end
Rails.application.routes.draw do

  #
  # Shoppe admin interface
  #
  mount Shoppe::Engine => "/shopman"

  #
  # Product browising
  #
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'

  #
  # Order status
  #
  get 'order/:token' => 'orders#status', :as => 'order_status'

  #
  # Basket
  #
  get 'basket' => 'orders#show', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'

  #
  # Checkout
  #
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]

  #
  # Static pages
  #
  get ':action', :controller => 'pages', :as => 'page'

  # 
  # Homepage
  #
  root :to => 'pages#home'

end

app/views/shared/_basket.html.haml
.basket
  - if has_order? && current_order.has_items?
    %p.quantity <b>#{pluralize current_order.total_items, 'item'}</b> in your shopping bag
    %p.amount <b>#{number_to_currency current_order.total_before_tax}</b> (ex. tax &amp; delivery)
    %p.buttons
      = link_to "View my bag", basket_path
      = link_to "Checkout", checkout_path, :class => 'checkout'

  - else
    %p.empty <b>Your shopping bag is empty.</b> 
    %p.empty How dare it be?! Why not add some stuff to it?

app/views/shared/_order_items.html.haml
%table.orderItems
  %thead
    %tr
      %td Qty
      %td Item
      %td Price
      %td= Shoppe.settings.tax_name
      %td Sub-Total
  %tbody
    - for item in order.order_items
      %tr
        %td.quantity
          - unless defined?(readonly)
            %span
              = link_to "+", adjust_basket_item_quantity_path(item.id), :method => :post, :class => 'ajax'
              = link_to "-", adjust_basket_item_quantity_path(item.id), :method => :delete, :class => 'ajax'
          = item.quantity
        %td.product
          = item.ordered_item.full_name
          - unless defined?(readonly)
            = link_to "Delete", remove_basket_item_path(item), :method => :delete, :class => 'delete ajax'
        %td.money.price= number_to_currency item.sub_total
        %td.money.tax= number_to_currency item.tax_amount
        %td.money.total= number_to_currency item.total
  %tfoot
    - if order.delivery_service
      %tr.delivery
        %td.method{:colspan => 4}
          - if defined?(readonly)
            = order.delivery_service.name
          - else
            = form_tag change_delivery_service_path do 
              = select_tag 'delivery_service', options_from_collection_for_select(order.available_delivery_services, :id, :name, order.delivery_service.id)
        %td.money= number_to_currency order.delivery_price
    %tr.subtotal
      %td{:colspan => 4} Total (excluding #{Shoppe.settings.tax_name})
      %td.money= number_to_currency order.total_before_tax
    %tr.tax
      %td{:colspan => 4}= Shoppe.settings.tax_name
      %td.money= number_to_currency order.tax
    %tr.total
      %td{:colspan => 4} Total
      %td.money= number_to_currency order.total

app/views/shared/_reasons.html.haml
%ul.reasons
  %li.support
    %h4 Free technical support
    %p We'll help you get your phone working. Just call or e-mail us.
  %li.quality
    %h4 Quality assurance
    %p We check all the produts we ship so you can rely on us.
  %li.delivery
    %h4 Next day delivery
    %p Order before 4pm and your order will be with you the next business day.